### ISSUE TITLE
Get rid of absolute positioning of title?

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace#72]
Is the absolute positioning still necessary? I was trying to make some spacing adjustments of the other elements and it's making things difficult.

**Comment by slifin** [comment]
The absolute positioning is to ensure this scenario doesn't happen: http://jsfiddle.net/cvz5vefc/
If we can drop that centering as a requirement then we can put it back into the flex container or there might be another solution using percentage widths, it just means we would be relying on the break point to collapse the menu into vertical rather than flex which can wrap automatically when space runs out

**Comment by kasbah** [comment]
Can we not just make the logo and the button bit the same width?

**Comment by slifin** [comment]
what do you think about this solution? 
https://jsfiddle.net/4w1brw1k/

**Comment by kasbah** [comment]
Looks good, yeah.

**Comment by kasbah** [comment]
I think this was solved with the redesign with #185
